JDP210301-16
piotr-grosicki/project-jdp-2103-01 pull request #13
Opened 2021-04-08 17:04 UTC by Maikody

2021-04-09 05:36 UTC, Necronum commented
Wszystkie testy przeszły poprawnie

2021-04-09 06:48 UTC, piotr-grosicki requested changes

2021-04-09 06:48 UTC, piotr-grosicki commented on src/test/java/com/kodilla/ecommercee/order/OrderCRUDTest.java
> +        Optional<User> userFromRepository = userRepository.findById(cartId);
dlaczego tutaj jest sprawdzany drugi raz user? chyba powinno byc sprawdzenie carta

2021-04-09 08:40 UTC, Maikody commented on src/test/java/com/kodilla/ecommercee/order/OrderCRUDTest.java
> +        Optional<User> userFromRepository = userRepository.findById(cartId);
noo jasne, juz poprawiam:)

2021-04-09 15:53 UTC, piotr-grosicki requested changes
konflikty

2021-04-10 07:00 UTC, piotr-grosicki approved these changes

2021-04-10 07:00 UTC, merged