Product controller implementation
piotr-grosicki/project-jdp-2103-01 pull request #15
Opened 2021-04-11 13:59 UTC by grego952

- added ProductMapper
- added ProductDbService
- injected ProductMapper and ProductDbService to Product Controller

2021-04-13 07:02 UTC, Maikody requested changes
1. Nie wiem czy to na pewno jest wymagane, ale ja zrozumiałem tak ze potrzebna jest jeszcze taka dodatkowa warstwa w postaci klasy Service, która będzie jakby pomiędzy controllerem a repozytorium, żeby nie było bezpośredniego polaczenia kontrolera i repo. Ja stworzyłem taka klasę OrderService, gdzie wstrzykuje sobie repo i mapper i ja używam już tylko w kontrolerze:)
Ale czy na bank to trzeba implementować  nie wiem (wydaje mi sie ze tak), ja w kazym razie widziałem na na necie taka architekturę, ale wiem ze na kursie wrzucaliśmy DbService prosto w kontroler:)

2. Mógłbyś tez zamienić @RequestParam na @PathVariable bo widzę ze już prawie wszędzie mamy właśnie @PathVariable

3. Obczailem jeszcze ze w ProductDTO nie mamy info o grupie tego produktu, a w sumie jak jest relacja to chyba pasuje to mieć:)

4. I ostatnie co wpadło mi w oko to na screenie w Jirze widać ze jak update'ujesz produkt to tak jakby go nie aktualizujesz tylko tworzy się nowy (w body request  jest id:4 ale w odpowiedzi id:5), no chyba ze to tylko zostało na screen'ie po jakimś poprzednim zapytaniu

To tyle:)

2021-04-15 13:25 UTC, Necronum requested changes

2021-04-15 13:25 UTC, Necronum commented on src/main/java/com/kodilla/ecommercee/mapper/ProductMapper.java
> +public class ProductMapper {
Dodałbym jeszcze mapToProductList (na wzór mapToProductDtoList) - można to potem wykorzystać w innych mapperach zamiast repository.

2021-04-16 07:09 UTC, Maikody commented
A wiesz uświadomiłem sobie jeszcze ze teraz po dodaniu tych set'ow w ten sposob przy aktualizowaniu pasowałoby jeszcze sprawdzić czy każde pole DTO nie jest nullem i tylko te które nie są update'owac, bo inaczej jak ktoś poda w JSONie tylko cenę to znulluje mu nazwę produktu w bazie, albo wymusić ze każde pole nie może być null (może ta adnotacja @NotNull sie sprawdzi), albo po prostu if'em sprawdzić, tak ja mam u siebie w orderService.

2021-04-17 15:03 UTC, Necronum approved these changes

2021-04-17 15:04 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +        Product product1 = productDbService.getProduct(id).get();
do przeniesienie do serwisu

2021-04-17 15:05 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/ProductNotFoundException.java
> +public class ProductNotFoundException extends Exception {
dodac http status code

2021-04-17 15:10 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/ProductDto.java
> +    //private Long id;
id jest potrzebne w dto

2021-04-19 17:17 UTC, Maikody approved these changes
Git:)

2021-04-19 18:12 UTC, merged