JDP210301-24
piotr-grosicki/project-jdp-2103-01 pull request #16
Opened 2021-04-11 14:08 UTC by Maikody

Hej,
wrzucam pull request z implementacja OrderControllera, dodałem tez małe zmiany w encjach:

1.  **GROUP** przy polu products adnotacja @JsonIgnoreProperties żeby nie było cyklicznych odwołan -> grupa wywołuje produkt a produkt znowu grupę,
2.  **PRODUCT** przy polu group adnotacja @JsonIgnoreProperties również żeby nie było cyklicznych wywolan i to samo przy polu products,
3.  **CART**:
	- przy polu products adnotacja @JsonIgnoreProperties oraz zmiana Cascade (nie może być ALL bo usuwalibyśmy w ogóle produkty z bazy)
	- przy polu user zmiana fetchType na EAGER bo był problem z lazy loadingiem

Wszystko możemy przedyskutować bo teraz przy tej implementacji mogą pojawić się jakieś większe konflikty. ale oby nie:)

2021-04-11 17:28 UTC, piotr-grosicki requested changes

2021-04-11 17:28 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +    @JsonIgnoreProperties("products")
to jest niedopuszczalne, nigdy nie przerzucamy encji na jsony. cala komunikacja opiera sie na DTO

2021-04-11 17:28 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
> +    public ResponseEntity<?> getOrderById(@PathVariable Long id) {
controllery maja zwracac klasy Dto, nie ResponseEntity zawierajace cokolwiek. Jezeli to jest zrobione tylko po to zeby obslugiwac 404 to lepiej rzucic wyjatkiem z serwisu ;)

2021-04-11 17:28 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
> +    @JsonIgnoreProperties("group")
to jest niedopuszczalne, nigdy nie przerzucamy encji na jsony. cala komunikacja opiera sie na DTO

2021-04-11 17:28 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/OrderDto.java
> +        User user;
klasy DTO nie moga zalezec od klasy, ktore nie sa DTO (tutaj sa to encje)

2021-04-11 17:28 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +    @JsonIgnoreProperties("products")
to jest niedopuszczalne, nigdy nie przerzucamy encji na jsony. cala komunikacja opiera sie na DTO

2021-04-11 17:28 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
> +        return orderService.updateOrder(id, orderDto);
tutaj to samo co wyzej, zwracamy OrderDto, jezeli go nie znajdzie to rzucamy wyjatkiem z HttpStatus 404

2021-04-11 17:28 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/service/OrderService.java
> +    public ResponseEntity<?> getOrderById(Long id) {
generalnie zasada jest taka, ze warstwa serwisow nic nie wie o http i controllerach a ResponseEntity jest mocno powiazane z http. Do zastsosowania uwagi, ktore zamiescilem w controllerze

2021-04-11 17:28 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/OrderDto.java
> +@Value
Value raczej nie jest odpowiednia adnotacja skoro pole ID moze byc nullem (zapis nowego zamowienia poprzez controller)

2021-04-11 17:28 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/mapper/OrderMapper.java
> +        return new ResponseStatusException(HttpStatus.BAD_REQUEST, s);
BadRequest nie powinien byc rzucany w momencie nie znalezienia zasobu - https://www.restapitutorial.com/httpstatuscodes.html - 404 (ale poprzez wyjatek ;))

2021-04-11 17:28 UTC, piotr-grosicki requested changes
projekt sie nie buduje

2021-04-11 17:30 UTC, piotr-grosicki requested changes

2021-04-11 17:30 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/OrderStatus.java
> +    public static Optional<OrderStatus> parseString(String value) {
kazdy enum ma metode `valueOf(String)`, ktora robi mniej wiecej to samo ;)

2021-04-12 15:24 UTC, grego952 approved these changes
Według mnie spoko

2021-04-13 07:51 UTC, piotr-grosicki approved these changes

2021-04-13 13:59 UTC, Necronum approved these changes

2021-04-14 19:25 UTC, merged