Cart entity tests
piotr-grosicki/project-jdp-2103-01 pull request #18
Opened 2021-04-13 19:52 UTC by Zephirus91

Cart entity tests

2021-04-14 05:58 UTC, grego952 requested changes
Konflikty

2021-04-14 19:34 UTC, Maikody commented
Jak usuniesz konflikty to chyba będzie wszystko git bo wydaje mi się ze testy są ok:)

2021-04-16 00:18 UTC, Zephirus91 commented
Teraz już powinno być dobrze :).

2021-04-16 05:19 UTC, grego952 approved these changes
Jest git :)

2021-04-16 07:01 UTC, Maikody commented
chyba znowu konflikt bo widzę ze rebase cos się wysypał

2021-04-16 12:22 UTC, merged