Jdp210301 23
piotr-grosicki/project-jdp-2103-01 pull request #19
Opened 2021-04-16 15:27 UTC by Zephirus91

Cart controller implementation

2021-04-17 15:18 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/CartNotFoundException.java
> +public class CartNotFoundException extends Exception {
response code

2021-04-17 15:19 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    public void createOrder(@RequestBody CartDto cartDto){
tworzenie carta w metodzie do tworzenia orderu :)

2021-04-17 15:19 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/CartDto.java
> +    private User user;
tutaj powinno byc userDto

2021-04-17 15:19 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/CartDto.java
> +    private List<Product> products;
tutaj powinno byc productDto

2021-04-20 08:06 UTC, Maikody approved these changes

2021-04-20 10:51 UTC, grego952 commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +                .orElseThrow(() -> new CartNotFoundException("Group not found!"));
Tutaj chyba powinno być "Cart not found!" :)

2021-04-20 17:39 UTC, Necronum requested changes

2021-04-20 17:39 UTC, Necronum commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +                .orElseThrow(() -> new CartNotFoundException("Group not found!"));
Popraw tutaj i reszta jest git ;)

2021-04-21 13:15 UTC, kmlyn approved these changes

2021-04-21 13:39 UTC, Necronum approved these changes

2021-04-21 15:22 UTC, grego952 approved these changes

2021-04-21 15:50 UTC, Maikody commented
wszytko na zielono to mozesz Tomek mergowac:)

2021-04-21 17:58 UTC, merged