JDP210301-4
piotr-grosicki/project-jdp-2103-01 pull request #2
Opened 2021-04-01 20:18 UTC by Maikody

OrderController - wstepna implementacja

2021-04-02 06:51 UTC, piotr-grosicki requested changes
projekt sie nie buduje: https://app.circleci.com/pipelines/github/piotr-grosicki/project-jdp-2103-01/6/workflows/0b7e484a-17b0-4e83-84e3-2d7906752ac5/jobs/7 . Lomboka dodaje sie troche w inny sposob, podejrzyj sobie w materialach z modulow jakie wpisy nalezy dodac zeby lombok zaczal dzialac

2021-04-02 06:53 UTC, piotr-grosicki requested changes

2021-04-02 06:53 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/OrderController.java
> +    public void addOrder(@Valid @RequestBody RESTOrderCommand command){
aplikacji nie piszemy w command patternie, metody maja przyjmowac obiekty `dto`

2021-04-02 06:53 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/OrderController.java
> +    public void updateOrder(@PathVariable Long id, @RequestBody RESTOrderCommand command) {
j.w.

2021-04-02 06:53 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/OrderController.java
> +    private static class RESTOrderCommand {
j.w. brakuje dto obslugujacego `Order`

2021-04-02 06:53 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/GenericEntity.java
> +    public void setValue(String value) {
tej klasy GenericEntity nie uzywamy, piszemy wlasne encje (w przypadku tego zadania bedzie to tylko `dto`)

2021-04-02 10:50 UTC, Maikody commented
Nanioslem poprawki i póki co w OrderMapper'ze zostawiłem GenericEntity i dopiero teraz wezmę się za klasę Order:)

2021-04-02 11:29 UTC, piotr-grosicki commented
> Nanioslem poprawki i póki co w OrderMapper'ze zostawiłem GenericEntity i dopiero teraz wezmę się za klasę Order:)

ale mapper w tym zadaniu nie powinien byc robiony, spojrz na inne PR. wystarczy ze zwracasz DTO i przyjmuejsz DTO jako parametr

2021-04-02 14:52 UTC, piotr-grosicki requested changes
konflikty

2021-04-03 08:36 UTC, piotr-grosicki approved these changes

2021-04-03 08:36 UTC, merged