JDP210301 3
piotr-grosicki/project-jdp-2103-01 pull request #5
Opened 2021-04-02 14:43 UTC by Necronum

- stworzono Product i ProductDto
- stworzono CartController
(pytanie czy potrzebny jest dodatkowo Cart i CartDto)

2021-04-02 14:52 UTC, piotr-grosicki requested changes

2021-04-02 14:52 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/CartController.java
>  public class CartController {
cart controller obsluguje glownie encje `Cart` (czyli dto `CartDto` a nie `ProductDto`)

2021-04-02 14:52 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    public List<ProductDto> createEmptyCart(){
powinien byc zwracany `CartDto`

2021-04-02 14:52 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    public List<ProductDto> getCart(){
powinien byc zwracany `CartDto`, brakuje id przekazywanego jako parametr metody

2021-04-02 14:52 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    public void addProductToCart(@RequestBody ProductDto productDto){
metoda aktualnie nie ma sensu, nie bedzie wiadomo do jakiego carta dodac dany produkt

2021-04-02 14:52 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    public void deleteProductFromCart(@RequestParam Long productId){
nie ma informacji z ktorego carta ma dany produkt byc usuniety

2021-04-02 14:52 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    public void createOrder(@RequestBody List<ProductDto> cart){
cart to cart a nie lista `ProductDto`

2021-04-02 14:52 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +public class Product {
ta klasa nie powinna powstac w tym zadaniu

2021-04-02 14:52 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/ProductDto.java
> +public class ProductDto {
ta klasa nie powinna powstac w tym zadaniu

2021-04-02 14:52 UTC, piotr-grosicki requested changes
konflikty

2021-04-02 16:00 UTC, piotr-grosicki requested changes

2021-04-02 16:00 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    public void addProductToCart(){
brakuje parametrow metody

2021-04-03 08:35 UTC, piotr-grosicki requested changes
konflikty

2021-04-03 08:41 UTC, Necronum commented
Poprawiono konflikty

2021-04-04 07:23 UTC, piotr-grosicki requested changes

2021-04-04 07:23 UTC, piotr-grosicki commented on build.gradle
> +    testCompileOnly 'org.projectlombok:lombok:1.18.12'
lombok jest tutaj drugi raz dodany (zle naprawione konflikty)

2021-04-06 12:08 UTC, piotr-grosicki approved these changes

2021-04-06 12:08 UTC, merged