Encja Group - implementacja
piotr-grosicki/project-jdp-2103-01 pull request #9
Opened 2021-04-06 06:02 UTC by Necronum

- implementacja encji Group

2021-04-06 12:10 UTC, piotr-grosicki requested changes
konflikty

2021-04-06 15:32 UTC, Necronum commented
Konflikty poprawione

2021-04-06 16:33 UTC, piotr-grosicki requested changes
konflikty

2021-04-07 06:14 UTC, piotr-grosicki approved these changes

2021-04-07 06:14 UTC, merged